### ISSUE TITLE
Processing algorithm to convert gridadmin.h5 to geopackage with vector layers 

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#1]
Input: gridadmin.h5
Output: geopackage with layers:

- obstacle
- cell
- pump
- pump_linestring
- node
- flowline

Most of the required functionality is available in https://github.com/nens/threedigrid

The layer names and order in the layer panel should be like this:
![image](https://user-images.githubusercontent.com/26224299/171401743-d1dce084-d32c-4fec-9a14-0686eb235890.png)

Please use the following QML's to style the layers (#15)

[styles.zip](https://github.com/nens/threedi-results-analysis/files/8813913/styles.zip)

Code should be something like this:

```
from threedigrid.admin.exporters.geopackage import GeopackageExporter
class Progress:
    def __init__(self):
        self.percentage = 0
    def update(self, count, total):
        if (count * 100) // total > self.percentage:
            self.percentage = (count * 100) // total
            print("Percentage done: %s" % self.percentage)
progress = Progress()
exporter = GeopackageExporter("/tmp/gridadmin.h5", "/tmp/bergermeer.gpkg")
exporter.export(progress.update)
```

**Comment by leendertvanwolfswinkel** [comment]
Further work on this in separate tickets

**Comment by leendertvanwolfswinkel** [comment]
On hold until https://github.com/nens/threedigrid/issues/163 is complete

**Comment by leendertvanwolfswinkel** [comment]
I got it working now. Feedback:

- [ ] Input widget for the gridadmin.h5 file now asks users to select a folder; should be a file with .h5 extension
- [ ] If I choose to output to temporary directory, I get the following error: 
```
{ 'INPUT' : 'C:\\Users\\leendert.vanwolfswin\\OneDrive - Nelen & Schuurmans\\Documents 1\\tuindorp\\resultaten\\sim_75756_tuindorp_oostzaan_water_balance_pump_without_endnode_test', 'OUTPUT' : 'TEMPORARY_OUTPUT' }

Traceback (most recent call last):
File "C:\Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\3Di Results Analysis/python/plugins\threedi-results-analysis\processing_provider\convert_to_gpkg.py", line 120, in processAlgorithm
exporter.export(progress.update)
File "C:\Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\3Di Results Analysis/python\threedigrid\admin\exporters\geopackage\default.py", line 91, in export
pumps.to_gpkg(self.gpkg_filename, progress_func=internal_func)
File "C:\Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\3Di Results Analysis/python\threedigrid\orm\models.py", line 112, in to_gpkg
exporter.save(
File "C:\Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\3Di Results Analysis/python\threedigrid\admin\exporters\geopackage\exporter.py", line 104, in save
data_source = self.driver.CreateDataSource(file_name)
File "C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages\GDAL-3.4.1-py3.9-win-amd64.egg\osgeo\ogr.py", line 522, in CreateDataSource
return _ogr.Driver_CreateDataSource(self, *args, **kwargs)
RuntimeError: sqlite3_open(C:/Users/leendert.vanwolfswin/AppData/Local/Temp/processing_vEOyzh/9925a26d9f8d4c03acdee3bbf2baac27/OUTPUT\out.gpkg) failed: unable to open database file

Execution failed after 0.93 seconden

```

- [ ]  Handle cases where the input file does not contain any obstacles (or pumps; all gridadmin files should contain nodes and flowlines). For example, this gridadmin.h5 that contains no obstacles ([gridadmin.zip](https://github.com/nens/threedi-results-analysis/files/8907396/gridadmin.zip)), gives me this error:
```
QGIS versie: 3.22.3-Białowieża
QGIS coderevisie: 1628765ec7
Qt versie: 5.15.2
Python versie: 3.9.5
GDAL versie: 3.4.1
GEOS versie: 3.10.0-CAPI-1.16.0
PROJ versie: Rel. 8.2.1, January 1st, 2022
PDAL versie: 2.3.0 (git-version: 9f35b7)
Algoritme begonnen om: 2022-06-15T10:05:57
Algoritme 'Convert gridadmin to GeoPackage' starten...
Parameters invoer:
{ 'INPUT' : 'C:\\Users\\leendert.vanwolfswin\\OneDrive - Nelen & Schuurmans\\Documents 1\\tuindorp\\resultaten\\sim_75756_tuindorp_oostzaan_water_balance_pump_without_endnode_test', 'OUTPUT' : 'C:\\Users\\leendert.vanwolfswin\\Downloads\\grid viz' }

Export done!
Skipping setting project CRS - the source file C:\Users\leendert.vanwolfswin\OneDrive - Nelen & Schuurmans\Documents 1\tuindorp\resultaten\sim_75756_tuindorp_oostzaan_water_balance_pump_without_endnode_test\gridadmin.h5 contained data with various CRS.
Execution completed in 31.13 seconden
Resultaten:
{}

Resultaatlagen laden
De volgende lagen werden niet juist gegenereerd.
• Obstacle_d47dae61_db75_452d_b7e3_175ab1e749c2
U kunt het 'paneel Logboekmeldingen' bekijken in het hoofdvenster van QGIS om meer informatie te vinden over het uitvoeren van dit algoritme.
```
