### ISSUE TITLE
TypeError: setValue(self, value: int): argument 1 has unexpected type 'float'

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#1047]
dacht met een clean sheet beginnen:
3di verwijderd
alle versies qgis verwijderd
alle profiles in AppData mapje verwijderd

nu heb ik de 3di modeller interface weer opnieuw geinstalleerd zowel met 'install default profile' en daarna zonder, beide keren deze melding als ik 3Di Results Analysis wil installeren:
 

daarna zegt ie wel 'plugin installed succesfully'
als ik dan 3di opnieuw opstart en als ik naar installed plugins ga staat 3di result analysis wel aangevinkt, maar niet in processing toolbox of toolbar te zien. aan en uit zetten geeft zelfde error.

Python error text:
2024-09-24T15:47:48     CRITICAL    Traceback (most recent call last):
              File "C:\PROGRA~1/3DIMOD~1.34/apps/qgis-ltr/./python\qgis\utils.py", line 401, in loadPlugin
              __import__(packageName)
              File "C:\PROGRA~1/3DIMOD~1.34/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\Users\rutger.wiebing\AppData\Roaming\3Di\QGIS3\profiles\default/python/plugins\threedi_results_analysis\__init__.py", line 57, in 
              dependencies.ensure_everything_installed()
              File "C:\Users\rutger.wiebing\AppData\Roaming\3Di\QGIS3\profiles\default/python/plugins\threedi_results_analysis\dependencies.py", line 150, in ensure_everything_installed
              if not _ensure_h5py_installed():
              ^^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\Users\rutger.wiebing\AppData\Roaming\3Di\QGIS3\profiles\default/python/plugins\threedi_results_analysis\dependencies.py", line 234, in _ensure_h5py_installed
              return _install_h5py(hdf5_version)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\Users\rutger.wiebing\AppData\Roaming\3Di\QGIS3\profiles\default/python/plugins\threedi_results_analysis\dependencies.py", line 253, in _install_h5py
              _install_dependencies([H5PY_DEPENDENCY], target_dir=_dependencies_target_dir())
              File "C:\Users\rutger.wiebing\AppData\Roaming\3Di\QGIS3\profiles\default/python/plugins\threedi_results_analysis\dependencies.py", line 527, in _install_dependencies
              bar.setValue((count / len(dependencies)) * 100)
             TypeError: setValue(self, value: int): argument 1 has unexpected type 'float'

**Comment by benvanbasten-ns** [comment]
@leendertvanwolfswinkel Let's postpone this one until we move to QGIS 3.34.10 (and python 3.12)
