### ISSUE TITLE
Vector layers as output of processing algorithm "Check schematisation"

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#1049]
Depends on nens/threedi-modelchecker#399

- [x] Split outputs in point, line, polygon and no geometry layers
- [x] Add all outputs to the project in a group
- [x] Styling files to be designed

**Comment by leendertvanwolfswinkel** [comment]
@margrietpalm ik heb het uitgeprobeerd maar kreeg helaas een foutmelding (zie hieronder)

Schematisatie:
https://nelenschuurmans-my.sharepoint.com/:u:/g/personal/leendert_vanwolfswinkel_nelen-schuurmans_nl/ESlvKztG_-FEqDh9bNjperwBKUcanQHLaC7sFz5c6SkFng?e=qmT7hM

```
QGIS version: 3.40.4-Bratislava
QGIS code revision: 4dd7d7e969
Qt version: 5.15.13
Python version: 3.12.9
GDAL version: 3.10.2
GEOS version: 3.13.0-CAPI-1.19.0
PROJ version: Rel. 9.5.1, December 1st, 2024
PDAL version: 2.8.3 (git-version: 56e405)
Algorithm started at: 2025-05-01T16:53:26
Algorithm 'Check Schematisation' starting…
Input parameters:
{ 'ADD_TO_PROJECT' : True, 'INPUT' : 'C:\\Users\\leendert.vanwolfswin\\Downloads\\Schiphol_integraal\\work in progress\\schematisation\\Schiphol_integraal.gpkg', 'OUTPUT' : 'TEMPORARY_OUTPUT' }

Traceback (most recent call last):
File "C:\Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\Release candidate (QGIS 3.40)/python/plugins\threedi_results_analysis\processing\schematisation_algorithms.py", line 239, in processAlgorithm
error_details = export_with_geom(error_list)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\leendert.vanwolfswin\AppData\Roaming\QGIS\QGIS3\profiles\Release candidate (QGIS 3.40)\python\plugins\nens_dependency_loader\deps\threedi_modelchecker\exporters.py", line 57, in export_with_geom
geom=error_row.geom.as_wkb() if hasattr(error_row, "geom") else None,
^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'bytes' object has no attribute 'as_wkb'

Execution failed after 41.85 seconds

Loading resulting layers
Algorithm 'Check Schematisation' finished
```

**Comment by leendertvanwolfswinkel** [comment]
@margrietpalm bij een andere schematisatie krijg ik een andere error: 

[Demo model Langaa.zip](https://github.com/user-attachments/files/20001178/Demo.model.Langaa.zip)

Dit gebeurt alleen als ik "Save to Temporary file" doe. Als ik wel een bestand als output kies krijg ik geen foutmelding. Als ik vervolgens de gemaakte geopackage probeer te openen in QGIS, krijg ik weer de melding dat het geen valide geopackage is.

```
QGIS version: 3.40.4-Bratislava
QGIS code revision: 4dd7d7e969
Qt version: 5.15.13
Python version: 3.12.9
GDAL version: 3.10.2
GEOS version: 3.13.0-CAPI-1.19.0
PROJ version: Rel. 9.5.1, December 1st, 2024
PDAL version: 2.8.3 (git-version: 56e405)
Algorithm started at: 2025-05-01T17:03:37
Algorithm 'Check Schematisation' starting…
Input parameters:
{ 'ADD_TO_PROJECT' : True, 'INPUT' : 'C:\\Users\\leendert.vanwolfswin\\Documents\\3Di\\Demo model Langaa\\work in progress\\schematisation\\Demo model Langaa.gpkg', 'OUTPUT' : 'TEMPORARY_OUTPUT' }

GeoPackage successfully written to C:/Users/leendert.vanwolfswin/AppData/Local/Temp/processing_RcbqKJ/1efee441e6f349f7bf57f6871e11f07a/OUTPUT.gpkg
Traceback (most recent call last):
File "C:\Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\Release candidate (QGIS 3.40)/python/plugins\threedi_results_analysis\processing\schematisation_algorithms.py", line 309, in postProcessAlgorithm
conn = ogr.Open(self.output_file_path)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\PROGRA~1\QGIS34~1.4\apps\Python312\Lib\site-packages\osgeo\ogr.py", line 7258, in Open
return _ogr.Open(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: `C:/Users/leendert.vanwolfswin/AppData/Local/Temp/processing_RcbqKJ/1efee441e6f349f7bf57f6871e11f07a/OUTPUT.gpkg' not recognized as being in a supported file format.

Execution completed in 2.25 seconds
Results:
  OUTPUT: [C:\Users\leendert.vanwolfswin\AppData\Local\Temp\processing_RcbqKJ\1efee441e6f349f7bf57f6871e11f07a\OUTPUT.gpkg](file:///C:/Users/leendert.vanwolfswin/AppData/Local/Temp/processing_RcbqKJ/1efee441e6f349f7bf57f6871e11f07a/OUTPUT.gpkg)

Loading resulting layers
Algorithm 'Check Schematisation' finished
```

**Comment by leendertvanwolfswinkel** [comment]
@margrietpalm klein verbeterpuntje: er zit geen file filter op de output file. Dat moet gpkg zijn, zodat ie ook vanzelf die extensie ervan maakt

**Comment by leendertvanwolfswinkel** [comment]
@margrietpalm laatste opmerkingen:
- Styling files heb ik gemaakt: [schematisation checker style files.zip](https://github.com/user-attachments/files/20004665/schematisation.checker.style.files.zip)
- Groep graag bovenaan de layer tree toevoegen ipv onderaan
- Naam van de groep: f"Check results: {name of input geopackage without extension}"
- Volgorde van de lagen: Point, Line, Polyon, No geom
- Namen van de lagen: "Point features", "Line features", "Polygon features", "Table features"

Het eindresultaat ziet er dan zo uit als het goed is:

![Image](https://github.com/user-attachments/assets/c21bf63b-c9b5-4842-8bfa-34b0931f871d)

**Comment by leendertvanwolfswinkel** [comment]
@margrietpalm toch nog een laatste opmerking/idee: we kunnen de checker results ook opslaan in de schematisatie geopackage. Dat maakt een aantal dingen in deze implementatie denk ik net wat makkelijker.

Voor een volgende feature waar ik op zit te broeden zou dat namelijk ook handig zijn: nens/threedi-modelchecker#467

**Comment by margrietpalm** [comment]
@leendertvanwolfswinkel is dit iets dat je nu nog wilt aanpassen als onderdeel van dit feature?

**Comment by leendertvanwolfswinkel** [comment]
@margrietpalm volgens mij werkt het helemaal goed! Ik had alleen bij het testen een paar keer het idee dat ie was vastgelopen op 100%. Tot ik snapte wat er gebeurt: hij gaat dan nog de geopackage maken, wat ook even duurt. Zou je de volgende aanpassing nog kunnen doen:

- Als wordt begonnen aan het runnen van de checker: `feedback.pushInfo("Checking schematisation....")`
- Als ie alle checks heeft gehad, staat de progress bar op 80%
- Als wordt begonnen aan het wegschrijven naar geopackage: `feedback.pushInfo("Writing checker results to geopackage....")`
- Tijdens het wegschrijven naar de geopackage wordt de laatste 20% gevuld

**Comment by margrietpalm** [comment]
@leendertvanwolfswinkel aanpassingen zijn gepushed. Output ziet er nu zo uit:

```
Algorithm started at: 2025-05-28T08:25:57
Algorithm 'Check Schematisation' starting…
Input parameters:
{ 'ADD_TO_PROJECT' : True, 'INPUT' : '/home/margriet/qgis_workdir/Demo Struisbeek 0D1D.gpkg', 'OUTPUT' : 'TEMPORARY_OUTPUT' }

Loading schematisation...
Checking schematisation...
Writing checker results to geopackage...
Adding layer 'Point features' to geopackage...
Adding layer 'Line features' to geopackage...
Adding layer 'Polygon features' to geopackage...
Adding layer 'Table features' to geopackage...
GeoPackage successfully written to file
Adding results to project...
Added results to layer 'Check results: Demo Struisbeek 0D1D'
Execution completed in 2.10 seconds
Results:
  OUTPUT: [/tmp/processing_XZGFjp/a77e1db8afc944cc89432f6800bc6ff0/OUTPUT.gpkg](file:///tmp/processing_XZGFjp/a77e1db8afc944cc89432f6800bc6ff0/OUTPUT.gpkg)

Loading resulting layers
Algorithm 'Check Schematisation' finished
```

Checking schematisation eindigt op 80% en na elke 'Adding layer' komt er 5% bij.

**Comment by leendertvanwolfswinkel** [comment]
@margrietpalm deze kan gemerged worden!
