### ISSUE TITLE
[animation-settings] Clicking "Relative" gives Python error

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#1052]
<img width="395" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGNxQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1d68f9a12775462d878a8ed7ef98c3143bcdce1f/image.png" alt="image.png" />

```
AttributeError: 'MapAnimatorSettings' object has no attribute 'nr_of_classes' 
Traceback (most recent call last):
  File "C:\Users\leendert.vanwolfswin\AppData\Roaming\3Di\QGIS3\profiles\3Di Staging/python/plugins\threedi_results_analysis\tool_animation\map_animator.py", line 568, in _restyle_and_update_nodes
    self._restyle(lines=False, nodes=True)
  File "C:\Users\leendert.vanwolfswin\AppData\Roaming\3Di\QGIS3\profiles\3Di Staging/python/plugins\threedi_results_analysis\tool_animation\map_animator.py", line 558, in _restyle
    self._style_node_layers(result_item, progress_bar)
  File "C:\Users\leendert.vanwolfswin\AppData\Roaming\3Di\QGIS3\profiles\3Di Staging/python/plugins\threedi_results_analysis\tool_animation\map_animator.py", line 494, in _style_node_layers
    current_node_settings.nr_of_classes,
AttributeError: 'MapAnimatorSettings' object has no attribute 'nr_of_classes'
```

**Comment by benvanbasten-ns** [comment]
@leendertvanwolfswinkel  fixed (on the animation_settings branch)
