### ISSUE TITLE
AttributeError when loading a QGIS project

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#1063]
How to reproduce:

- Empty QGIS project
- Add some data, e.g. basemap or something
- Save QGIS project
- Load QGIS project

```
An error has occurred while executing Python code: 

AttributeError: 'NoneType' object has no attribute 'firstChildElement' 
Traceback (most recent call last):
  File "C:\Users\leendert.vanwolfswin\AppData\Roaming\3Di\QGIS3\profiles\default/python/plugins\threedi_results_analysis\threedi_plugin.py", line 267, in read
    if not tool.read(tool_node):
  File "C:\Users\leendert.vanwolfswin\AppData\Roaming\3Di\QGIS3\profiles\default/python/plugins\threedi_results_analysis\tool_watershed\watershed_analysis.py", line 40, in read
    watershed_node = xml_elem.firstChildElement("water_shed")
AttributeError: 'NoneType' object has no attribute 'firstChildElement'
```

**Comment by benvanbasten-ns** [comment]
@leendertvanwolfswinkel I could not reproduce the issue, but might have identified the issue in the code. Could you test it? (master)

**Comment by leendertvanwolfswinkel** [comment]
Issue does no longer come up, I guess it is fixed
