### ISSUE TITLE
animatie werkt niet goed voor alle variabelen die je kan kiezen

### ISSUE THREAD

**Issue by ghost** [nens/threedi-results-analysis#115]
- veranderen van waterlevel naar infiltration_rate geeft deze melding (animatie):
IndexError: index 33247 is out of bounds for axis 0 with size 33247
Traceback (most recent call last):
  File "C:/Users/Arnold.vantveld/.qgis2/python/plugins\ThreeDiToolbox\views\map_animator.py", line 94, in on_node_parameter_change
    self.update_results()
  File "C:/Users/Arnold.vantveld/.qgis2/python/plugins\ThreeDiToolbox\views\map_animator.py", line 223, in update_results
    value = values[ids - 1]
IndexError: index 33247 is out of bounds for axis 0 with size 33247

- discharge_pump in drop-downbox in animatie geeft:
IndexError: index 8 is out of bounds for axis 0 with size 8
Traceback (most recent call last):
  File "C:/Users/Arnold.vantveld/.qgis2/python/plugins\ThreeDiToolbox\views\map_animator.py", line 86, in on_line_parameter_change
    self.update_results()
  File "C:/Users/Arnold.vantveld/.qgis2/python/plugins\ThreeDiToolbox\views\map_animator.py", line 223, in update_results
    value = values[ids - 1]
IndexError: index 8 is out of bounds for axis 0 with size 8

**Comment by bastiaan-roos** [comment]
De animatie tool is nog steeds een experimentele tool die niet is afgemaakt (wachten is op budget om dit te doen).
De slider houd nog geen rekening met het aantal tijdstappen dat beschikbaar is in (met name) de (aggregatie) netCDF's. 
Zie RFC #98 om dit goed af te maken.
