### ISSUE TITLE
import_sufhyd werkt niet

### ISSUE THREAD

**Issue by ghost** [nens/threedi-results-analysis#117]
import_sufhyd geeft deze melding bij het starten:
ImportError: No module named utils.threedi_database

Traceback (most recent call last):
  File "C:/Users/Arnold.vantveld/.qgis2/python/plugins\ThreeDiToolbox\threedi_toolbox.py", line 148, in run_script
    mod = imp.load_source(name, module_path)
  File "C:/Users/Arnold.vantveld/.qgis2/python/plugins\ThreeDiToolbox\commands\toolbox_tools\stap 2 - Data conversie en inlezen\import_sufhyd.py", line 7, in 
    from ThreeDiToolbox.views.import_sufhyd_dialog import (
  File "C:/OSGEO4~1/apps/qgis-ltr/./python\qgis\utils.py", line 572, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/Arnold.vantveld/.qgis2/python/plugins\ThreeDiToolbox\views\import_sufhyd_dialog.py", line 10, in 
    from utils.threedi_database import get_databases
  File "C:/OSGEO4~1/apps/qgis-ltr/./python\qgis\utils.py", line 572, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: No module named utils.threedi_database

**Comment by jackieleng** [comment]
Importprobleem.
Fix: https://github.com/nens/threedi-qgis-plugin/pull/118
