### ISSUE TITLE
Dependency conflict with 3Di Toolbox

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#21]
Converting gridadmin.h5 to geopackage fails when 3Di Toolbox is also installed / active.

Please suggest one or more ways to solve this. 

Example traceback when running GeopackageExporter.export() with 3Di Toolbox installed:
```
Traceback (most recent call last):
  File "C:\OSGeo4W\apps\Python39\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "<string>", line 11, in <module>
  File "C:\Users/zaap/AppData/Roaming/QGIS/QGIS3\profiles\3di/python\threedigrid\admin\exporters\geopackage\default.py", line 100, in export
    lines.to_gpkg(
  File "C:\Users/zaap/AppData/Roaming/QGIS/QGIS3\profiles\3di/python\threedigrid\orm\models.py", line 112, in to_gpkg
    exporter.save(
  File "C:\Users/zaap/AppData/Roaming/QGIS/QGIS3\profiles\3di/python\threedigrid\admin\exporters\geopackage\exporter.py", line 149, in save
    field_type = get_field_type(self.model, field_name)
  File "C:\Users/zaap/AppData/Roaming/QGIS/QGIS3\profiles\3di/python\threedigrid\admin\exporters\geopackage\exporter.py", line 58, in get_field_type
    return model._get_field(field_name).type
  File "C:\Users/zaap/AppData/Roaming/QGIS/QGIS3\profiles\3di/python\threedigrid\orm\base\models.py", line 141, in _get_field
    return super().__getattribute__(field_name)
AttributeError: 'Lines' object has no attribute 'line_geometries'
```

**Comment by ldebek** [comment]
@leendertvanwolfswinkel Fix available within ThreediToolbox on branch: https://github.com/nens/ThreeDiToolbox/tree/removing_patched_threedigrid

**Comment by leendertvanwolfswinkel** [comment]
Amazing fix 🥇 hahaha

Tested all the tools that might be affected, no problems found. Branch https://github.com/nens/ThreeDiToolbox/tree/removing_patched_threedigrid can be merged with master afaik
