### ISSUE TITLE
On calc_structure_statistics.py and calc_manhole_statistics.py error

### ISSUE THREAD

**Issue by ghost** [nens/threedi-results-analysis#27]
Traceback (most recent call last):
  File "C:/Users/ber.albers/.qgis2/python/plugins\threedi-qgis-plugin\threedi_toolbox.py", line 144, in run_script
    mod = imp.load_source(name, module_path)
  File "C:/Users/ber.albers/.qgis2/python/plugins\threedi-qgis-plugin\commands\toolbox_tools\stap 5 - Resultaten nabewerken\calc_structure_statistics.py", line 8, in 
    from ThreeDiToolbox.stats.ncstats import NcStats
  File "C:/PROGRA~1/QGISWI~1/apps/qgis-ltr/./python\qgis\utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: No module named ThreeDiToolbox.stats.ncstats

**Comment by ghost** [comment]
wrong named plugin
