### ISSUE TITLE
schematisation checker 'Table' object has no attribute 'base_mapper' 

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-results-analysis#497]
Checked the schematisation checker in the plugin version 1.14 DEV

I get the following error:

An error has occurred while executing Python code: 

AttributeError: 'Table' object has no attribute 'base_mapper' 
Traceback (most recent call last):
  File "C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\toolbox dev1.14/python/plugins\ThreeDiToolbox\tool_commands\schematisation_checker\controller.py", line 47, in on_run
    success = self.command.run_it(threedi_db, output_file_path)
  File "C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\toolbox dev1.14/python/plugins\ThreeDiToolbox\tool_commands\schematisation_checker\command.py", line 91, in run_it
    model_errors = check.get_invalid(session)
  File "C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\toolbox dev1.14/python\threedi_modelchecker\checks\other.py", line 260, in get_invalid
    start_node, self.start_node
  File "C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\toolbox dev1.14/python\sqlalchemy\orm\query.py", line 2010, in join
    from_joinpoint=from_joinpoint)
  File "", line 2, in _join
  File "C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\toolbox dev1.14/python\sqlalchemy\orm\base.py", line 201, in generate
    fn(self, *args[1:], **kw)
  File "C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\toolbox dev1.14/python\sqlalchemy\orm\query.py", line 2154, in _join
    outerjoin, full, create_aliases, prop)
  File "C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\toolbox dev1.14/python\sqlalchemy\orm\query.py", line 2227, in _join_left_to_right
    self._join_to_left(l_info, left, right, onclause, outerjoin, full)
  File "C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\toolbox dev1.14/python\sqlalchemy\orm\query.py", line 2341, in _join_to_left
    if ent.corresponds_to(left):
  File "C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\toolbox dev1.14/python\sqlalchemy\orm\query.py", line 4074, in corresponds_to
    entity.common_parent(self.entity_zero)
  File "C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\toolbox dev1.14/python\sqlalchemy\orm\mapper.py", line 2392, in common_parent
    return self.base_mapper is other.base_mapper
AttributeError: 'Table' object has no attribute 'base_mapper'

Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.4.9-Madeira Madeira, 54585165bb 

Python Path:
C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python
C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\toolbox dev1.14/python
C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\toolbox dev1.14/python/plugins
C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python/plugins
C:\Program Files\QGIS 3.4\bin\python37.zip
C:\PROGRA~1\QGIS3~1.4\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib
C:\Program Files\QGIS 3.4\bin
C:\PROGRA~1\QGIS3~1.4\apps\Python37
C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib\site-packages\Pythonwin
C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\toolbox dev1.14/python

**Comment by Jonasvsl** [comment]
same for noordpolder:

An error has occurred while executing Python code: 

AttributeError: 'Table' object has no attribute 'base_mapper' 
Traceback (most recent call last):
  File "C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\toolbox dev1.14/python/plugins\ThreeDiToolbox\tool_commands\schematisation_checker\controller.py", line 47, in on_run
    success = self.command.run_it(threedi_db, output_file_path)
  File "C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\toolbox dev1.14/python/plugins\ThreeDiToolbox\tool_commands\schematisation_checker\command.py", line 91, in run_it
    model_errors = check.get_invalid(session)
  File "C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\toolbox dev1.14/python\threedi_modelchecker\checks\other.py", line 260, in get_invalid
    start_node, self.start_node
  File "C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\toolbox dev1.14/python\sqlalchemy\orm\query.py", line 2010, in join
    from_joinpoint=from_joinpoint)
  File "", line 2, in _join
  File "C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\toolbox dev1.14/python\sqlalchemy\orm\base.py", line 201, in generate
    fn(self, *args[1:], **kw)
  File "C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\toolbox dev1.14/python\sqlalchemy\orm\query.py", line 2154, in _join
    outerjoin, full, create_aliases, prop)
  File "C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\toolbox dev1.14/python\sqlalchemy\orm\query.py", line 2227, in _join_left_to_right
    self._join_to_left(l_info, left, right, onclause, outerjoin, full)
  File "C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\toolbox dev1.14/python\sqlalchemy\orm\query.py", line 2341, in _join_to_left
    if ent.corresponds_to(left):
  File "C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\toolbox dev1.14/python\sqlalchemy\orm\query.py", line 4074, in corresponds_to
    entity.common_parent(self.entity_zero)
  File "C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\toolbox dev1.14/python\sqlalchemy\orm\mapper.py", line 2392, in common_parent
    return self.base_mapper is other.base_mapper
AttributeError: 'Table' object has no attribute 'base_mapper'


Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.4.9-Madeira Madeira, 54585165bb 

Python Path:
C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python
C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\toolbox dev1.14/python
C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\toolbox dev1.14/python/plugins
C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python/plugins
C:\Program Files\QGIS 3.4\bin\python37.zip
C:\PROGRA~1\QGIS3~1.4\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib
C:\Program Files\QGIS 3.4\bin
C:\PROGRA~1\QGIS3~1.4\apps\Python37
C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib\site-packages\Pythonwin
C:/Users/jonas.vanschrojenste/AppData/Roaming/QGIS/QGIS3\profiles\toolbox dev1.14/python

**Comment by RichardB9** [comment]
Seems to be caused of `sqlalchemy` version. The ThreediToolbox provides sqlalchemy `1.1.18` while the modelchecker has it pinned on `1.3.1`

Will look more into it...
