### ISSUE TITLE
No module named 'alembic' 

### ISSUE THREAD

**Issue by lisannewapstra** [nens/threedi-results-analysis#553]
New installations of the threeditoolbox result in an error and the plugin can't be used. 
3 users with this problem so far (via colleague Cécile and tested by Jasper and Lisanne via new user profile)
Please fix soon as many more may follow. 

@Jonasvsl  @reinout 

**Couldn't load plugin 'ThreeDiToolbox' due to an error when calling its classFactory() method** 

**ModuleNotFoundError: No module named 'alembic'**
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/lisanne.wapstra/AppData/Roaming/QGIS/QGIS3\profiles\lisanne21april/python/plugins\ThreeDiToolbox\__init__.py", line 42, in classFactory
    dependencies.check_importability()
  File "C:/Users/lisanne.wapstra/AppData/Roaming/QGIS/QGIS3\profiles\lisanne21april/python/plugins\ThreeDiToolbox\dependencies.py", line 249, in check_importability
    imported_package = importlib.import_module(package)
  File "C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "", line 1006, in _gcd_import
  File "", line 983, in _find_and_load
  File "", line 967, in _find_and_load_unlocked
  File "", line 677, in _load_unlocked
  File "", line 728, in exec_module
  File "", line 219, in _call_with_frames_removed
  File "C:/Users/lisanne.wapstra/AppData/Roaming/QGIS/QGIS3\profiles\lisanne21april/python\threedi_modelchecker\__init__.py", line 1, in 
    from .model_checks import *  # NOQA
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/lisanne.wapstra/AppData/Roaming/QGIS/QGIS3\profiles\lisanne21april/python\threedi_modelchecker\model_checks.py", line 3, in 
    from .schema import ModelSchema
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/lisanne.wapstra/AppData/Roaming/QGIS/QGIS3\profiles\lisanne21april/python\threedi_modelchecker\schema.py", line 4, in 
    from alembic import command
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'alembic'

Python Path:
C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python
C:/Users/lisanne.wapstra/AppData/Roaming/QGIS/QGIS3\profiles\lisanne21april/python
C:/Users/lisanne.wapstra/AppData/Roaming/QGIS/QGIS3\profiles\lisanne21april/python/plugins
C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS3~1.16\apps\Python37
C:\PROGRA~1\QGIS3~1.16\apps\Python37\Scripts
C:\Program Files\QGIS 3.16\bin\python37.zip
C:\PROGRA~1\QGIS3~1.16\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib
C:\Program Files\QGIS 3.16\bin
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\Pythonwin
C:/Users/lisanne.wapstra/AppData/Roaming/QGIS/QGIS3\profiles\lisanne21april/python

**Comment by lisannewapstra** [comment]
aangepast met nieuwe release
