### ISSUE TITLE
3Di Toolbox does not work under QGIS 3.20

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#575]
On startup, I get the following error.

This may be an issue for the new LTR (3.22) as well. 

```
Kon plug-in 'ThreeDiToolbox' niet laden 

FileNotFoundError: [WinError 2] The system cannot find the file specified 
Traceback (most recent call last):
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 313, in loadPlugin
    __import__(packageName)
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\test_3di_1_20/python/plugins\ThreeDiToolbox\__init__.py", line 26, in 
    dependencies.ensure_everything_installed()
  File "C:\Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\test_3di_1_20/python/plugins\ThreeDiToolbox\dependencies.py", line 85, in ensure_everything_installed
    _ensure_h5py_installed()
  File "C:\Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\test_3di_1_20/python/plugins\ThreeDiToolbox\dependencies.py", line 125, in _ensure_h5py_installed
    hdf5_version = _get_hdf5_version()
  File "C:\Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\test_3di_1_20/python/plugins\ThreeDiToolbox\dependencies.py", line 375, in _get_hdf5_version
    process = subprocess.Popen(
  File "C:\OSGeo4W\apps\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\OSGeo4W\apps\Python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified


Python versie: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS versie: 3.20.0-Odense Odense, decaadbb31 

Python pad:
C:/OSGeo4W/apps/qgis/./python
C:/Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\test_3di_1_20/python
C:/Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\test_3di_1_20/python/plugins
C:/OSGeo4W/apps/qgis/./python/plugins
C:\OSGeo4W\bin\python39.zip
C:\OSGeo4W\apps\Python39\DLLs
C:\OSGeo4W\apps\Python39\lib
C:\OSGeo4W\bin
C:\OSGeo4W\apps\Python39
C:\OSGeo4W\apps\Python39\lib\site-packages
C:\OSGeo4W\apps\Python39\lib\site-packages\win32
C:\OSGeo4W\apps\Python39\lib\site-packages\win32\lib
C:\OSGeo4W\apps\Python39\lib\site-packages\Pythonwin
C:/Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\test_3di_1_20/python
```

**Comment by lisannewapstra** [comment]
Please make sure it keeps working on the LTR 3.16 till October.
