### ISSUE TITLE
Sideview tool does not (always) work on channels

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#594]
How to reproduce:

Open the model & results from this download: https://we.tl/t-GnJkNNWtUc
Draw a sideview from connection node 748 to connection node 95

The following Exception is raised:

```
KeyError: 124 
Traceback (most recent call last):
  File "C:/Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ThreeDiToolbox\tool_sideview\sideview_view.py", line 916, in canvasReleaseEvent
    self.callback_on_select(selected_points, transformed_point)
  File "C:/Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ThreeDiToolbox\tool_sideview\sideview_view.py", line 1699, in on_route_point_select
    self.active_sideview.set_sideprofile(self.route.path, self.route.path_points)
  File "C:/Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ThreeDiToolbox\tool_sideview\sideview_view.py", line 402, in set_sideprofile
    sub_begin_node = self.node_dict[sub_begin_node_id]
KeyError: 124


Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.16.9-Hannover Hannover, 9f8d2f7942 
```

**Comment by ldebek** [comment]
Fix available on branch: https://github.com/nens/ThreeDiToolbox/tree/sideview_tool_fix

**Comment by leendertvanwolfswinkel** [comment]
I tested it with another dataset (https://we.tl/t-goPDod6JTr), but as soon as I click on the Sideview Tool button, I get this error:

```
Er is een fout opgetreden bij het uitvoeren van Python code: 

KeyError: 521 
Traceback (most recent call last):
  File "C:\Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\test 3Di Toolbox 20220523/python/plugins\ThreeDiToolbox\tool_sideview\sideview.py", line 72, in run
    new_widget = SideViewDockWidget(
  File "C:\Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\test 3Di Toolbox 20220523/python/plugins\ThreeDiToolbox\tool_sideview\sideview_view.py", line 1136, in __init__
    ) = self.create_combined_layers(
  File "C:\Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\test 3Di Toolbox 20220523/python/plugins\ThreeDiToolbox\tool_sideview\sideview_view.py", line 1493, in create_combined_layers
    crs_def = profiles[p["definition_id"]]
KeyError: 521


Python versie: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS versie: 3.22.3-Białowieża Białowieża, 1628765ec7 

Python pad:
C:/PROGRA~1/QGIS32~1.3/apps/qgis/./python
C:/Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\test 3Di Toolbox 20220523/python
C:/Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\test 3Di Toolbox 20220523/python/plugins
C:/PROGRA~1/QGIS32~1.3/apps/qgis/./python/plugins
C:\Program Files\QGIS 3.22.3\bin\python39.zip
C:\PROGRA~1\QGIS32~1.3\apps\Python39\DLLs
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib
C:\Program Files\QGIS 3.22.3\bin
C:\PROGRA~1\QGIS32~1.3\apps\Python39
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages\GDAL-3.4.1-py3.9-win-amd64.egg
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages\Pythonwin
```

**Comment by ldebek** [comment]
@leendertvanwolfswinkel Looks like similar issue, but not exactly the same. It seems that tool works on schematisation attached to the ticket, but not on your data... Error message is also refering to the different part of the tool. I will have a look at it anyway.

**Comment by leendertvanwolfswinkel** [comment]
Original issue is fixed. New issue in new ticket: #635
