### ISSUE TITLE
Installing v1.34 still fails on QGIS 3.22 / python 3.9

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#620]
Not sure if v1.34 is already supposed to support QGIS 3.22 / python 3.9, but it surely doesn't work for me yet:

```
Couldn't load plugin 'ThreeDiToolbox' 

FileNotFoundError: [WinError 2] The system cannot find the file specified 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS32~1.3/apps/qgis/./python\qgis\utils.py", line 401, in loadPlugin
    __import__(packageName)
  File "C:\PROGRA~1/QGIS32~1.3/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ThreeDiToolbox\__init__.py", line 26, in 
    dependencies.ensure_everything_installed()
  File "C:\Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ThreeDiToolbox\dependencies.py", line 86, in ensure_everything_installed
    _ensure_h5py_installed()
  File "C:\Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ThreeDiToolbox\dependencies.py", line 126, in _ensure_h5py_installed
    hdf5_version = _get_hdf5_version()
  File "C:\Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ThreeDiToolbox\dependencies.py", line 376, in _get_hdf5_version
    process = subprocess.Popen(
  File "C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified


Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.22.3-Białowieża Białowieża, 1628765ec7 

Python Path:
C:\Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\threedi_beta_processing
C:/PROGRA~1/QGIS32~1.3/apps/qgis/./python
C:/Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS32~1.3/apps/qgis/./python/plugins
C:\Program Files\QGIS 3.22.3\bin\python39.zip
C:\PROGRA~1\QGIS32~1.3\apps\Python39\DLLs
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib
C:\Program Files\QGIS 3.22.3\bin
C:\PROGRA~1\QGIS32~1.3\apps\Python39
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages\GDAL-3.4.1-py3.9-win-amd64.egg
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages\Pythonwin
C:/Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\leendert.vanwolfswin\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\bgtinlooptool
C:\Users\leendert.vanwolfswin\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\bgtinlooptool
.
C:\Users\leendert.vanwolfswin\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\threedi-results-analysis\deps\threedigrid-1.2.0-py2.py3-none-any.whl
C:\Users\leendert.vanwolfswin\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\threedi-results-analysis\deps\threedigrid-1.2.0-py2.py3-none-any.whl
```

**Comment by reinout** [comment]
No new LTR yet. If that happens I'll make sure to signal the change by upping the version number to 2.x :-)
