### ISSUE TITLE
Install dependencies in sub-folder of ThreeDiToolbox

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#621]
Python packages are currently installed in `{user_profile_dir}\python\`

Consequence of this is that when the plugin is uninstalled or updated, the dependencies are not removed. 

Instead, dependencies should be installed in a subdirectory of the plugin's home folder, e.g. `{user_profile_dir}\python\plugins\ThreeDiToolbox\deps`

This might influence other plugins that make use of the dependencies installed by the ThreeDiToolbox (but I don't think so)

**Comment by leendertvanwolfswinkel** [comment]
I expect that this change will fix issues like this:

> Older version of 3Di Toolbox is installed
> User attempts to update 3Di Toolbox
> User gets this error:

```
2022-06-08T14:35:19     CRITICAL    Traceback (most recent call last):
              File "C:\PROGRA~1/3DIMOD~1.22/apps/qgis-ltr/./python\qgis\utils.py", line 423, in _startPlugin
              plugins[packageName] = package.classFactory(iface)
              File "C:\Users\jonas.vanschrojenste\AppData\Roaming\3Di\QGIS3\profiles\default/python/plugins\ThreeDiToolbox\__init__.py", line 42, in classFactory
              dependencies.check_importability()
              File "C:\Users\jonas.vanschrojenste\AppData\Roaming\3Di\QGIS3\profiles\default/python/plugins\ThreeDiToolbox\dependencies.py", line 247, in check_importability
              imported_package = importlib.import_module(package)
              File "C:\PROGRA~1\3DIMOD~1.22\apps\Python39\lib\importlib\__init__.py", line 127, in import_module
              return _bootstrap._gcd_import(name[level:], package, level)
              File "", line 1030, in _gcd_import
              File "", line 1007, in _find_and_load
              File "", line 986, in _find_and_load_unlocked
              File "", line 680, in _load_unlocked
              File "", line 855, in exec_module
              File "", line 228, in _call_with_frames_removed
              File "C:\Users\jonas.vanschrojenste\AppData\Roaming\3Di\QGIS3\profiles\default/python\netCDF4\__init__.py", line 3, in
              from ._netCDF4 import *
              File "C:\PROGRA~1/3DIMOD~1.22/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
             ModuleNotFoundError: No module named 'netCDF4._netCDF4'
```

**Comment by leendertvanwolfswinkel** [comment]
I tested installing [0207a59](https://github.com/nens/ThreeDiToolbox/pull/642/commits/0207a5950c94087bbbc23143a953b7be662a54c3) on user profile that already contained version 2.0 of the 3Di Toolbox.

I got the error shown below. If I remember correctly, `UpgradeFailedError` was introduced in the latest release of `threedi_modelchecker`.

If I install in a virgin user profile, I don't run into any trouble.

```Couldn't load plugin 'ThreeDiToolbox' due to an error when calling its classFactory() method 

ImportError: cannot import name 'UpgradeFailedError' from 'threedi_modelchecker.errors' (C:\Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\default/python\threedi_modelchecker\errors.py) 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS32~1.3/apps/qgis/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ThreeDiToolbox\__init__.py", line 58, in classFactory
    from .threedi_plugin import ThreeDiPlugin
  File "C:\PROGRA~1/QGIS32~1.3/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ThreeDiToolbox\threedi_plugin.py", line 14, in 
    from ThreeDiToolbox.tool_result_selection.models import TimeseriesDatasourceModel
  File "C:\PROGRA~1/QGIS32~1.3/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ThreeDiToolbox\tool_result_selection\__init__.py", line 1, in 
    from ThreeDiToolbox.tool_result_selection.result_selection import ThreeDiResultSelection
  File "C:\PROGRA~1/QGIS32~1.3/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ThreeDiToolbox\tool_result_selection\result_selection.py", line 11, in 
    from ThreeDiToolbox.tool_result_selection import result_selection_view
  File "C:\PROGRA~1/QGIS32~1.3/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ThreeDiToolbox\tool_result_selection\result_selection_view.py", line 14, in 
    from threedi_modelchecker.spatialite_versions import get_spatialite_version
  File "C:\PROGRA~1/QGIS32~1.3/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users\leendert.vanwolfswin\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ThreeDiToolbox\deps\threedi_modelchecker\spatialite_versions.py", line 7, in 
    from threedi_modelchecker.errors import UpgradeFailedError
ImportError: cannot import name 'UpgradeFailedError' from 'threedi_modelchecker.errors' (C:\Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\default/python\threedi_modelchecker\errors.py)


Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.22.3-Białowieża Białowieża, 1628765ec7 

Python Path:
C:\Users\leendert.vanwolfswin\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ThreeDiToolbox\deps
C:/PROGRA~1/QGIS32~1.3/apps/qgis/./python
C:/Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS32~1.3/apps/qgis/./python/plugins
C:\Program Files\QGIS 3.22.3\bin\python39.zip
C:\PROGRA~1\QGIS32~1.3\apps\Python39\DLLs
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib
C:\Program Files\QGIS 3.22.3\bin
C:\PROGRA~1\QGIS32~1.3\apps\Python39
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages\GDAL-3.4.1-py3.9-win-amd64.egg
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages\Pythonwin
C:/Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\leendert.vanwolfswin\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\threedi-results-analysis\deps\threedigrid-1.2.3-py2.py3-none-any.whl
C:\Users\leendert.vanwolfswin\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\threedi-results-analysis\deps\threedigrid-1.2.3-py2.py3-none-any.whl
```
