### ISSUE TITLE
Improvements to installation

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#625]
- [x] Package wheels for all pure-python dependencies with the plugin (as it is done in github.com/nens/threedi-api-qgis-client)
- [x] When installing dependencies interrupt the user's activities as little as possible (i.e. no cmd windows, or only a single cmd window), tell users what is going on and how the process is progressing (e.g. progress bar or "installing required python dependency 3/4...") 
- [x] #621 
- [x] In the current implementation, when you install the plugin, then restart QGIS, you will still see command prompt windows. This should also not happen; I'm not sure what command is being executed and if this is intended, but the user should not be bothered with this.

**Comment by leendertvanwolfswinkel** [comment]
Tested again, but unfortunately it I did not manage to complete the install when having an old QGIS 3.16 / 3Di Toolbox 1.34 install in my profile (common situation for most of our users).

Sidenote: please do not use "ThreediToolbox" in messages for users; for users the name of the plugin is "3Di Toolbox"

What I did:
- Started out with an old QGIS 3.16 / 3Di Toolbox 1.34 install in my profile
- Started up QGIS 3.22
- Installed  [3Di Toolbox v2.2](https://github.com/nens/ThreeDiToolbox/commit/5a0b51ee5dd62532642d4aae755f124e88dee690)
- No 'please restart qgis' popup, but did get a python error:
```
Couldn't load plugin 'ThreeDiToolbox'

FileNotFoundError: [WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS32~1.3/apps/qgis/./python\qgis\utils.py", line 401, in loadPlugin
    __import__(packageName)
  File "C:\PROGRA~1/QGIS32~1.3/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\3Di Toolbox installatieverbeteringen/python/plugins\ThreeDiToolbox\__init__.py", line 28, in 
    dependencies.ensure_everything_installed()
  File "C:\Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\3Di Toolbox installatieverbeteringen/python/plugins\ThreeDiToolbox\dependencies.py", line 86, in ensure_everything_installed
    dialog.setBar(bar)
  File "C:\Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\3Di Toolbox installatieverbeteringen/python/plugins\ThreeDiToolbox\dependencies.py", line 126, in _ensure_h5py_installed
    # In case some libraries are already imported, we cannot uninstall
  File "C:\Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\3Di Toolbox installatieverbeteringen/python/plugins\ThreeDiToolbox\dependencies.py", line 376, in _get_hdf5_version
    python_interpreter = _get_python_interpreter()
  File "C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]
QGIS version: 3.22.3-Białowieża Białowieża, 1628765ec7

Python Path:
C:/PROGRA~1/QGIS32~1.3/apps/qgis/./python
C:/Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\3Di Toolbox installatieverbeteringen/python
C:/Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\3Di Toolbox installatieverbeteringen/python/plugins
C:/PROGRA~1/QGIS32~1.3/apps/qgis/./python/plugins
C:\Program Files\QGIS 3.22.3\bin\python39.zip
C:\PROGRA~1\QGIS32~1.3\apps\Python39\DLLs
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib
C:\Program Files\QGIS 3.22.3\bin
C:\PROGRA~1\QGIS32~1.3\apps\Python39
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages\GDAL-3.4.1-py3.9-win-amd64.egg
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages\Pythonwin
C:/Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\3Di Toolbox installatieverbeteringen/python
```
- Get message that 3Di Toolbox was installed successfully (standard message from plugin manager), but plugin doesn't work yet, i.e. is not loaded
- Restart QGIS
- Get a neat progress bar showing me the 3Di Toolbox install progress
- When it is finished, I get the message "Please restart QGIS to complete the installation process of ThreediToolbox"
- I click OK, QGIS continues loading, then produces another error:
```
ImportError: cannot import name '_ccallback_c' from 'scipy._lib' (C:\Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\temp/python\scipy\_lib\__init__.py) 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS32~1.3/apps/qgis/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\temp/python/plugins\ThreeDiToolbox\__init__.py", line 58, in classFactory
    from .threedi_plugin import ThreeDiPlugin
  File "C:\PROGRA~1/QGIS32~1.3/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\temp/python/plugins\ThreeDiToolbox\threedi_plugin.py", line 10, in 
    from ThreeDiToolbox.processing.provider import ThreediProvider
  File "C:\PROGRA~1/QGIS32~1.3/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\temp/python/plugins\ThreeDiToolbox\processing\provider.py", line 5, in 
    from ThreeDiToolbox.processing.threedidepth_algorithm import ThreediDepth
  File "C:\PROGRA~1/QGIS32~1.3/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\temp/python/plugins\ThreeDiToolbox\processing\threedidepth_algorithm.py", line 31, in 
    from threedidepth.calculate import calculate_waterdepth
  File "C:\PROGRA~1/QGIS32~1.3/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users\leendert.vanwolfswin\AppData\Roaming\QGIS\QGIS3\profiles\temp\python\plugins\ThreeDiToolbox\deps\threedidepth\calculate.py", line 11, in 
    from scipy.interpolate import LinearNDInterpolator
  File "C:\PROGRA~1/QGIS32~1.3/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\temp/python\scipy\__init__.py", line 147, in 
    from scipy._lib._ccallback import LowLevelCallable
  File "C:\PROGRA~1/QGIS32~1.3/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\temp/python\scipy\_lib\_ccallback.py", line 1, in 
    from . import _ccallback_c
ImportError: cannot import name '_ccallback_c' from 'scipy._lib' (C:\Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\temp/python\scipy\_lib\__init__.py)


Python versie: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS versie: 3.22.3-Białowieża Białowieża, 1628765ec7 

Python pad:
C:\Users\leendert.vanwolfswin\AppData\Roaming\QGIS\QGIS3\profiles\temp\python\plugins\ThreeDiToolbox\deps
C:/PROGRA~1/QGIS32~1.3/apps/qgis/./python
C:/Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\temp/python
C:/Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\temp/python/plugins
C:/PROGRA~1/QGIS32~1.3/apps/qgis/./python/plugins
C:\Program Files\QGIS 3.22.3\bin\python39.zip
C:\PROGRA~1\QGIS32~1.3\apps\Python39\DLLs
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib
C:\Program Files\QGIS 3.22.3\bin
C:\PROGRA~1\QGIS32~1.3\apps\Python39
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages\GDAL-3.4.1-py3.9-win-amd64.egg
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages\Pythonwin
C:/Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\temp/python
```
- When QGIS is loaded, I restart again and get a new '3Di Toolbox install progress' window (for a short time). Then again the Please restart QGIS message and the same error (`ImportError: cannot import name '_ccallback_c' from 'scipy._lib' `)
- Ad infinitum
- PS if I manually remove the scipy folders from {qgis profile folder}\python, and restart QGIS, I have no issues

**Comment by benvanbasten-ns** [comment]
@leendertvanwolfswinkel your first issue is because the app h5stat.exe is no longer present in QGIS (See issue #584 and #575). Perhaps these issue can be closed (and/or documented)
