### ISSUE TITLE
Stats tool error when using newest Modeller Interface

### ISSUE THREAD

**Issue by JJFlorian** [nens/threedi-results-analysis#626]
QGIS + plugin install does not result in the error

QGIS version
3.16.16-Hannover
QGIS code revision
[f5778a89df](https://github.com/qgis/QGIS/commit/f5778a89df)

Compiled against Qt
5.11.2
Running against Qt
5.11.2

Compiled against GDAL/OGR
3.1.4
Running against GDAL/OGR
3.1.4

Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3

Compiled against SQLite
3.29.0
Running against SQLite
3.29.0

PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0

QWT Version
6.1.3
QScintilla2 Version
2.10.8

Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020

OS Version
Windows 10 (10.0)

Active python plugins
pdokservicesplugin;
profiletool;
quick_map_services;
ThreeDiCustomizations;
ThreeDiToolbox;
threedi_models_and_simulations;
valuetool;
db_manager;
MetaSearch;
processing

2022-04-11T09:21:50 WARNING Traceback (most recent call last):
File "C:\Users\jonas.vanschrojenste\AppData\Roaming\3Di\QGIS3\\profiles\default/python\sqlalchemy\engine\base.py", line 1277, in _execute_context
cursor, statement, parameters, context
File "C:\Users\jonas.vanschrojenste\AppData\Roaming\3Di\QGIS3\\profiles\default/python\sqlalchemy\engine\default.py", line 608, in do_execute
cursor.execute(statement, parameters)
sqlite3.OperationalError: no such module: VirtualKNN

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "C:\Users\jonas.vanschrojenste\AppData\Roaming\3Di\QGIS3\\profiles\default/python/plugins\ThreeDiToolbox\tool_statistics\tools\statistics.py", line 147, in run
self.db_meta = self.db.get_metadata()
File "C:\Users\jonas.vanschrojenste\AppData\Roaming\3Di\QGIS3\\profiles\default/python/plugins\ThreeDiToolbox\tool_statistics\utils\statistics_database.py", line 45, in get_metadata
metadata.reflect(extend_existing=True)
File "C:\Users\jonas.vanschrojenste\AppData\Roaming\3Di\QGIS3\\profiles\default/python\sqlalchemy\sql\schema.py", line 4622, in reflect
Table(name, self, **reflect_opts)
File "", line 2, in __new__
File "C:\Users\jonas.vanschrojenste\AppData\Roaming\3Di\QGIS3\\profiles\default/python\sqlalchemy\util\deprecations.py", line 139, in warned
return fn(*args, **kwargs)
File "C:\Users\jonas.vanschrojenste\AppData\Roaming\3Di\QGIS3\\profiles\default/python\sqlalchemy\sql\schema.py", line 563, in __new__
metadata._remove_table(name, schema)
File "C:\Users\jonas.vanschrojenste\AppData\Roaming\3Di\QGIS3\\profiles\default/python\sqlalchemy\util\langhelpers.py", line 70, in __exit__
with_traceback=exc_tb,
File "C:\Users\jonas.vanschrojenste\AppData\Roaming\3Di\QGIS3\\profiles\default/python\sqlalchemy\util\compat.py", line 182, in raise_
raise exception
File "C:\Users\jonas.vanschrojenste\AppData\Roaming\3Di\QGIS3\\profiles\default/python\sqlalchemy\sql\schema.py", line 558, in __new__
table._init(name, metadata, *args, **kw)
File "C:\Users\jonas.vanschrojenste\AppData\Roaming\3Di\QGIS3\\profiles\default/python\sqlalchemy\sql\schema.py", line 652, in _init
resolve_fks=resolve_fks,
File "C:\Users\jonas.vanschrojenste\AppData\Roaming\3Di\QGIS3\\profiles\default/python\sqlalchemy\sql\schema.py", line 676, in _autoload
_extend_on=_extend_on,
File "C:\Users\jonas.vanschrojenste\AppData\Roaming\3Di\QGIS3\\profiles\default/python\sqlalchemy\engine\base.py", line 1653, in run_callable
return callable_(self, *args, **kwargs)
File "C:\Users\jonas.vanschrojenste\AppData\Roaming\3Di\QGIS3\\profiles\default/python\sqlalchemy\engine\default.py", line 485, in reflecttable
table, include_columns, exclude_columns, resolve_fks, **opts
File "C:\Users\jonas.vanschrojenste\AppData\Roaming\3Di\QGIS3\\profiles\default/python\sqlalchemy\engine\reflection.py", line 665, in reflecttable
table_name, schema, **table.dialect_kwargs
File "C:\Users\jonas.vanschrojenste\AppData\Roaming\3Di\QGIS3\\profiles\default/python\sqlalchemy\engine\reflection.py", line 391, in get_columns
self.bind, table_name, schema, info_cache=self.info_cache, **kw
File "", line 2, in get_columns
File "C:\Users\jonas.vanschrojenste\AppData\Roaming\3Di\QGIS3\\profiles\default/python\sqlalchemy\engine\reflection.py", line 52, in cache
ret = fn(self, con, *args, **kw)
File "C:\Users\jonas.vanschrojenste\AppData\Roaming\3Di\QGIS3\\profiles\default/python\sqlalchemy\dialects\sqlite\base.py", line 1724, in get_columns
connection, pragma, table_name, schema=schema
File "C:\Users\jonas.vanschrojenste\AppData\Roaming\3Di\QGIS3\\profiles\default/python\sqlalchemy\dialects\sqlite\base.py", line 2183, in _get_table_pragma
cursor = connection.execute(statement)
File "C:\Users\jonas.vanschrojenste\AppData\Roaming\3Di\QGIS3\\profiles\default/python\sqlalchemy\engine\base.py", line 1003, in execute
return self._execute_text(object_, multiparams, params)
File "C:\Users\jonas.vanschrojenste\AppData\Roaming\3Di\QGIS3\\profiles\default/python\sqlalchemy\engine\base.py", line 1178, in _execute_text
parameters,
File "C:\Users\jonas.vanschrojenste\AppData\Roaming\3Di\QGIS3\\profiles\default/python\sqlalchemy\engine\base.py", line 1317, in _execute_context
e, statement, parameters, cursor, context
File "C:\Users\jonas.vanschrojenste\AppData\Roaming\3Di\QGIS3\\profiles\default/python\sqlalchemy\engine\base.py", line 1511, in _handle_dbapi_exception
sqlalchemy_exception, with_traceback=exc_info[2], from_=e
File "C:\Users\jonas.vanschrojenste\AppData\Roaming\3Di\QGIS3\\profiles\default/python\sqlalchemy\util\compat.py", line 182, in raise_
raise exception
File "C:\Users\jonas.vanschrojenste\AppData\Roaming\3Di\QGIS3\\profiles\default/python\sqlalchemy\engine\base.py", line 1277, in _execute_context
cursor, statement, parameters, context
File "C:\Users\jonas.vanschrojenste\AppData\Roaming\3Di\QGIS3\\profiles\default/python\sqlalchemy\engine\default.py", line 608, in do_execute
cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such module: VirtualKNN
[SQL: PRAGMA main.table_info("KNN")]
(Background on this error at: http://sqlalche.me/e/13/e3q8)

**Comment by leendertvanwolfswinkel** [comment]
Most probably fixed when #631 is completed

**Comment by leendertvanwolfswinkel** [comment]
@JJFlorian please provide the dataset for which this error occured

**Comment by Patrick-Nijman** [comment]
@JJFlorian It's unclear what this is about or how we can fix it. Could you follow-up on Thursday make an issue-only-servicedesk ticket or close this issue? 

Thanks!

Patrick
