### ISSUE TITLE
SideView tool: KeyError

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#635]
This error arises only for specific datasets, e.g. (https://we.tl/t-goPDod6JTr)

How to reproduce: load the data using the 3Di Toolbox, Click on the Sideview Tool button

The following error is raised:

```
Er is een fout opgetreden bij het uitvoeren van Python code: 

KeyError: 521 
Traceback (most recent call last):
  File "C:\Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\test 3Di Toolbox 20220523/python/plugins\ThreeDiToolbox\tool_sideview\sideview.py", line 72, in run
    new_widget = SideViewDockWidget(
  File "C:\Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\test 3Di Toolbox 20220523/python/plugins\ThreeDiToolbox\tool_sideview\sideview_view.py", line 1136, in __init__
    ) = self.create_combined_layers(
  File "C:\Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\test 3Di Toolbox 20220523/python/plugins\ThreeDiToolbox\tool_sideview\sideview_view.py", line 1493, in create_combined_layers
    crs_def = profiles[p["definition_id"]]
KeyError: 521


Python versie: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS versie: 3.22.3-Białowieża Białowieża, 1628765ec7 

Python pad:
C:/PROGRA~1/QGIS32~1.3/apps/qgis/./python
C:/Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\test 3Di Toolbox 20220523/python
C:/Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\test 3Di Toolbox 20220523/python/plugins
C:/PROGRA~1/QGIS32~1.3/apps/qgis/./python/plugins
C:\Program Files\QGIS 3.22.3\bin\python39.zip
C:\PROGRA~1\QGIS32~1.3\apps\Python39\DLLs
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib
C:\Program Files\QGIS 3.22.3\bin
C:\PROGRA~1\QGIS32~1.3\apps\Python39
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages\GDAL-3.4.1-py3.9-win-amd64.egg
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages\Pythonwin
```

**Comment by ldebek** [comment]
This one looks like a data issue for me which should be detected by schematization checker. Issue is that there are `cross_section_location` rows (with `definition_id == 521`) which are not represented within `cross_section_location_view` layer.
![image](https://user-images.githubusercontent.com/11883222/179515973-e1e47c47-dbac-4f3f-8fe1-0180669238fb.png)

**Comment by ldebek** [comment]
Temporary fix available on branch: `water_balance_and_sideview_fixes`
