### ISSUE TITLE
Statistics Tool error IndexError: index 0 is out of bounds for axis 0 with size 0

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#638]
When running the Statistics tool on this dataset [tuindorp_with_missing_surface_level.zip](https://github.com/nens/ThreeDiToolbox/files/8813059/tuindorp_with_missing_surface_level.zip), a warning popup message is shown about a missing surface level value (which is good). But I still also get a Python error. If the error is related to the fact that a surface level is missing, please catch the error.

```
Er is een fout opgetreden bij het uitvoeren van Python code: 

IndexError: index 0 is out of bounds for axis 0 with size 0 
Traceback (most recent call last):
  File "C:\Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\test 3Di Toolbox 20220523/python/plugins\ThreeDiToolbox\tool_statistics\tools\statistics.py", line 172, in run
    self.get_manhole_attributes_and_statistics()
  File "C:\Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\test 3Di Toolbox 20220523/python/plugins\ThreeDiToolbox\tool_statistics\tools\statistics.py", line 343, in get_manhole_attributes_and_statistics
    ri = int(np.where(manhole_idx == idx)[0][0])
IndexError: index 0 is out of bounds for axis 0 with size 0


Python versie: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS versie: 3.22.3-Białowieża Białowieża, 1628765ec7 

Python pad:
C:/PROGRA~1/QGIS32~1.3/apps/qgis/./python
C:/Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\test 3Di Toolbox 20220523/python
C:/Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\test 3Di Toolbox 20220523/python/plugins
C:/PROGRA~1/QGIS32~1.3/apps/qgis/./python/plugins
C:\Program Files\QGIS 3.22.3\bin\python39.zip
C:\PROGRA~1\QGIS32~1.3\apps\Python39\DLLs
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib
C:\Program Files\QGIS 3.22.3\bin
C:\PROGRA~1\QGIS32~1.3\apps\Python39
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages\GDAL-3.4.1-py3.9-win-amd64.egg
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages\Pythonwin
```

**Comment by leendertvanwolfswinkel** [comment]
I get the same behaviour with this dataset: https://we.tl/t-ysE0ptbAYG and also for yet another dataset (tolkamer). so it does not seem to be specific to the tuindorp dataset

**Comment by leendertvanwolfswinkel** [comment]
The error is not raised when all surface levels are filled in, so missing surface levels are a probable cause

**Comment by leendertvanwolfswinkel** [comment]
can no longer reproduce this either... odd.
