### ISSUE TITLE
Connect Watershed Tool to new results manager and make independent from spatialite / gridadmin.sqlite

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#668]

**Comment by leendertvanwolfswinkel** [comment]
- [x] Use Node layer instead of target nodes
- [x] Dropdown to select simulation result
- [x] Save group & layer ids of watershed tool output layers in Result Manager to prevent saving duplicate layers after reloading qgis project.
- [x] Create separate output layers for each grid and result
![image](https://github.com/nens/ThreeDiToolbox/assets/97883955/bcaf9538-7aef-486b-b8d4-7fb33c89deb5)
- [x] Change result layer group name when result is changed AND VICE VERSA
- Only show one result

Additional items: 

- [x] Reset styling when watershed tool is closed
- [x] Mark layers as removable when tool is closed
- [x] dealen met de situatie: tool staat nog aan, gebruiker slaat project op en sluit project/qgis. Bij heropening project wil je dan geen niet-verwijderbare lagen hebben

**Comment by leendertvanwolfswinkel** [comment]
Nice! Seems to work great for 99%

Some review comments:
- [x] Smoothing of the 'result watershed' polygons doesn't work anymore. I think in some cases this is actually what users would want. Can you add a checkbox 'smooth result watersheds' to the 'outputs' section, checked by default? 
- [ ] The Result Flowlines (1D) layer is empty, probably related to the message `2023-06-06T21:34:06     CRITICAL    Laag Result flowlines (1D) : Kon attribuut "kcu": Waarde "2d line" is geen getal niet opslaan`
- [ ] I got the following error, but I don't know exactly what I did. Perhaps it is really a weird corner case
```Er is een fout opgetreden bij het uitvoeren van Python code: 

AttributeError: 'QgsCategorizedSymbolRenderer' object has no attribute 'rootRule' 
Traceback (most recent call last):
  File "C:\Users\leendert.vanwolfswin\AppData\Roaming\3Di\QGIS3\profiles\3Di Results Analysis/python/plugins\threedi_results_analysis\tool_watershed\watershed_analysis_dockwidget.py", line 1126, in result_sets_count_changed
    self.spinbox_browse_result_sets_value_changed()
  File "C:\Users\leendert.vanwolfswin\AppData\Roaming\3Di\QGIS3\profiles\3Di Results Analysis/python/plugins\threedi_results_analysis\tool_watershed\watershed_analysis_dockwidget.py", line 1116, in spinbox_browse_result_sets_value_changed
    self.gq.filter = [self.spinBoxBrowseResultSets.value()]
  File "C:\Users\leendert.vanwolfswin\AppData\Roaming\3Di\QGIS3\profiles\3Di Results Analysis/python/plugins\threedi_results_analysis\tool_watershed\watershed_analysis_dockwidget.py", line 200, in filter
    self.update_layer_filters()
  File "C:\Users\leendert.vanwolfswin\AppData\Roaming\3Di\QGIS3\profiles\3Di Results Analysis/python/plugins\threedi_results_analysis\tool_watershed\watershed_analysis_dockwidget.py", line 232, in update_layer_filters
    self.target_node_layer.renderer().rootRule().children()[0].setFilterExpression(
AttributeError: 'QgsCategorizedSymbolRenderer' object has no attribute 'rootRule'
```

**Comment by leendertvanwolfswinkel** [comment]
Data / steps to reproduce needed
