### ISSUE TITLE
Computational grid: generating gridadmin from sqlite fails for schematisations without DEM

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#676]
When running the algorithm `Generate gridadmin` with a sqlite like [SSW Medemblik - 0D1D.zip](https://github.com/nens/ThreeDiToolbox/files/9112376/SSW.Medemblik.-.0D1D.zip) that does not refer to a DEM (0D/1D schematisation) gives the following error: 
```
Reading DEM settings from: C:\Users\rebecca.vanweesep\Documents\3Di-modellen\SSW Medemblik - 0D1D\work in progress\schematisation\SSW Medemblik - 0D1D.sqlite|layername=v2_global_settings

Traceback (most recent call last):


File "C:\Users\rebecca.vanweesep\AppData\Roaming\3Di\QGIS3\profiles\Gridadmin test/python/plugins\ThreeDiToolbox\processing\results_analysis\grid_creation.py", line 84, in processAlgorithm
set_dem_path = os.path.join(input_spatialite_dir, set_dem_rel_path)
File "C:\PROGRA~1\3DIMOD~1.22\apps\Python39\lib\ntpath.py", line 117, in join
genericpath._check_arg_types('join', path, *paths)
File "C:\PROGRA~1\3DIMOD~1.22\apps\Python39\lib\genericpath.py", line 152, in _check_arg_types
raise TypeError(f'{funcname}() argument must be str, bytes, or '
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'QVariant'
```

**Comment by ldebek** [comment]
Available on branch: `computational_grid_improvements`
