### ISSUE TITLE
Import sufhyd does not work because it expects column 'pipe_quality'

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#728]
Servicedesk ticket: 2212 0025

If you try to import a sufhyd file ([HWA_Borax.zip](https://github.com/nens/ThreeDiToolbox/files/10164949/HWA_Borax.zip)) to a spatialite with the current schema version (209) or higher, it will produce the error that is given below. The column `pipe_quality` has been removed in (I think) schema version 207.

Tasks: 
- [x] Remove pipe_quality from the code of import_sufhyd
- [x] #726

```
An error has occurred while executing Python code: 

KeyError: 'pipe_quality' 
Traceback (most recent call last):
  File "C:\Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ThreeDiToolbox\tool_commands\import_sufhyd\import_sufhyd_dialog.py", line 133, in on_accept
    self.command.run_it(self.filename, db_set, settings["db_type"])
  File "C:\Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ThreeDiToolbox\tool_commands\import_sufhyd\command.py", line 62, in run_it
    importer.run_import()
  File "C:\Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ThreeDiToolbox\tool_commands\import_sufhyd\import_sufhyd_main.py", line 105, in run_import
    commit_counts = self.write_data_to_db(data)
  File "C:\Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ThreeDiToolbox\tool_commands\import_sufhyd\import_sufhyd_main.py", line 554, in write_data_to_db
    del pipe["pipe_quality"]
KeyError: 'pipe_quality'


Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.22.3-Białowieża Białowieża, 1628765ec7 

Python Path:
C:\Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\threedi_beta_processing
C:\Users\leendert.vanwolfswin\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ThreeDiToolbox\deps
C:/PROGRA~1/QGIS32~1.3/apps/qgis/./python
C:/Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS32~1.3/apps/qgis/./python/plugins
C:\Program Files\QGIS 3.22.3\bin\python39.zip
C:\PROGRA~1\QGIS32~1.3\apps\Python39\DLLs
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib
C:\Program Files\QGIS 3.22.3\bin
C:\PROGRA~1\QGIS32~1.3\apps\Python39
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages\GDAL-3.4.1-py3.9-win-amd64.egg
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages\Pythonwin
C:/Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\default/python
```

**Comment by arjanverkerk** [comment]
Can the pipe_quality not resurface when importing older sufhyds? (I have no idea what I'm talking about)

**Comment by leendertvanwolfswinkel** [comment]
No, pipe quality is not a thing in sufhyd
