### ISSUE TITLE
bug project path

### ISSUE THREAD

**Issue by jackieleng** [nens/threedi-results-analysis#77]
Bug van Arnold:

Deze melding krijg ik als ik een lokale QGIS file opstart (zonder resultaten):

ValueError: no path specified

Traceback (most recent call last):
  File "C:/Users/Arnold.vantveld/.qgis2/python/plugins\ThreeDiToolbox\utils\qprojects.py", line 254, in save_setting_to_project
    value = self._get_relative_path(value)
  File "C:/Users/Arnold.vantveld/.qgis2/python/plugins\ThreeDiToolbox\utils\qprojects.py", line 153, in _get_relative_path
    rel_path = os.path.relpath(file_path, home)
  File "C:\OSGEO4~1\apps\Python27\lib\ntpath.py", line 498, in relpath
    raise ValueError("no path specified")
ValueError: no path specified

**Comment by jackieleng** [comment]
fixed
