### ISSUE TITLE
SQLAlchemy 2.0 support

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#793]
threedi-schema is now pinned to 0.214.4 because it no longer supports SQLAlchemy 1.3 -> Update SQLAlchemy to 1.4, or even better 2.0, as 2.0 seems to provide a pure python package. @arjanverkerk 

implement on master as well as refactor branch

**Comment by leendertvanwolfswinkel** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Modeller-Interface-61e574104cc38a001fb287de/issues/nens/ThreeDiToolbox/793?planning-poker) with Zenhub @benvanbasten-ns

**Comment by arjanverkerk** [comment]
@leendertvanwolfswinkel We need some new releases of our dependencies to support sqlalchemy 2 and ideally the latest threedi-schema:

Releases that support SQLAlchemy>=2.0 of:

- threedi-modelchecker
- condenser

Releases that support threedi-schema>=0.216:

- hydxlib
- threedigrid-builder

**Comment by benvanbasten-ns** [comment]
@arjanverkerk 

When loading a schematisation via the old result manager, layer_tree_manager:_on_set_schematisation() crashes on threedi_db.fix_spatial_indices(). I guess due to the update to SQLAlchemy 2.0. Could you have a look?

**Comment by benvanbasten-ns** [comment]
[15:59] Casper van der Wel
die "fix spatial indices" zit ook hier: https://github.com/nens/threedi-schema/blob/master/threedi_schema/application/schema.py#L172

**Comment by benvanbasten-ns** [comment]
Traceback (most recent call last):  File "C:\Users\ben.vanbasten\AppData\Roaming\3Di\QGIS3\profiles\default/python/plugins\threedi_results_analysis\utils\layer_tree_manager.py", line 182, in _on_set_schematisation    threedi_db.fix_spatial_indices()  File "C:\Users\ben.vanbasten\AppData\Roaming\3Di\QGIS3\profiles\default/python/plugins\threedi_results_analysis\utils\threedi_database.py", line 225, in fix_spatial_indices    missing_index_tables = self.get_missing_index_tables(expected_index_table_names)  File "C:\Users\ben.vanbasten\AppData\Roaming\3Di\QGIS3\profiles\default/python/plugins\threedi_results_analysis\utils\threedi_database.py", line 155, in get_missing_index_tables    existing_tables = self.engine.table_names()AttributeError: 'Engine' object has no attribute 'table_names'

**Comment by arjanverkerk** [comment]
I ported relevant changes to the master branch: 

https://docs.3di.live/threeditoolbox-dev/ThreeDiToolbox-verkerk-sqlalchemy2.zip

It may need some extra testing because the unit tests may not cover all sqlalchemy usecases.

**Comment by leendertvanwolfswinkel** [comment]
@arjanverkerk  Import sufhyd does not work yet

I tried with this spatialite [https://app.zenhub.com/files/55498704/baf42e7b-6e9e-4138-b744-77932325986c/download](https://app.zenhub.com/files/55498704/baf42e7b-6e9e-4138-b744-77932325986c/download)

And this sufhyd file: 
[https://app.zenhub.com/files/55498704/6f01e858-15c0-4d66-881d-24062b4b7a92/download](https://app.zenhub.com/files/55498704/6f01e858-15c0-4d66-881d-24062b4b7a92/download)

Which led to this error: 

```
Traceback (most recent call last):
File "C:\Users\leendert.vanwolfswin\AppData\Roaming\3Di\QGIS3\profiles\From the developers desk\python\plugins\ThreeDiToolbox\deps\sqlalchemy\orm\strategy_options.py", line 2300, in _parse_attr_argument
insp: InspectionAttr = inspect(attr) # type: ignore
File "C:\Users\leendert.vanwolfswin\AppData\Roaming\3Di\QGIS3\profiles\From the developers desk\python\plugins\ThreeDiToolbox\deps\sqlalchemy\inspection.py", line 118, in inspect
raise exc.NoInspectionAvailable(
sqlalchemy.exc.NoInspectionAvailable: No inspection system is available for object of type <class 'str'>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "C:\Users\leendert.vanwolfswin\AppData\Roaming\3Di\QGIS3\profiles\From the developers desk/python/plugins\ThreeDiToolbox\processing\schematisation_algorithms.py", line 321, in processAlgorithm
importer.run_import()
File "C:\Users\leendert.vanwolfswin\AppData\Roaming\3Di\QGIS3\profiles\From the developers desk/python/plugins\ThreeDiToolbox\processing\deps\sufhyd\import_sufhyd_main.py", line 132, in run_import
commit_counts = self.write_data_to_db(data)
File "C:\Users\leendert.vanwolfswin\AppData\Roaming\3Di\QGIS3\profiles\From the developers desk/python/plugins\ThreeDiToolbox\processing\deps\sufhyd\import_sufhyd_main.py", line 442, in write_data_to_db
.options(load_only("id", "code"))
File "C:\Users\leendert.vanwolfswin\AppData\Roaming\3Di\QGIS3\profiles\From the developers desk\python\plugins\ThreeDiToolbox\deps\sqlalchemy\orm\strategy_options.py", line 2353, in load_only
_, lead_element, _ = _parse_attr_argument(attrs[0])
File "C:\Users\leendert.vanwolfswin\AppData\Roaming\3Di\QGIS3\profiles\From the developers desk\python\plugins\ThreeDiToolbox\deps\sqlalchemy\orm\strategy_options.py", line 2302, in _parse_attr_argument
raise sa_exc.ArgumentError(
sqlalchemy.exc.ArgumentError: expected ORM mapped attribute for loader strategy argument

Execution failed after 1.91 seconds
```
