### ISSUE TITLE
Result aggregation: Pump support

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#861]
- [ ] Add aggregation variable "Pumps - Discharge pump"

The reason this does not exist yet is that Pumps are a separate model in threedigrid, next to `Lines` and `Nodes`. Also, Pumps can have / be represented as a Linestring geometry or a Point geometry, depending on the pump having a end node. This messes up some of the logic in the Result aggregation tool

**Comment by leendertvanwolfswinkel** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Modeller-Interface-61e574104cc38a001fb287de/issues/nens/ThreeDiToolbox/861?planning-poker) with Zenhub @arjanverkerk @benvanbasten-ns

**Comment by Overmeen** [comment]
tested and approved

**Comment by Overmeen** [comment]
Tested on a couple schematisation. Two failures:

[Result 1: operational_forecast_Khasab (no pumps in model)](https://we.tl/t-Smh5IzLt9o)
[Result 2: test (1 pump in model)](https://we.tl/t-zur2pAczDp)

**Traceback 1:**
File "C:\Users\Stijn.Overmeen\AppData\Roaming\3Di\QGIS3\profiles\testing/python/plugins\threedi_results_analysis\utils\threedi_result_aggregation\base.py", line 1216, in aggregate_threedi_results
    pump_results[new_column_name] = time_aggregate(
  File "C:\Users\Stijn.Overmeen\AppData\Roaming\3Di\QGIS3\profiles\testing/python/plugins\threedi_results_analysis\utils\threedi_result_aggregation\base.py", line 385, in time_aggregate
    timeseries, tintervals = prepare_timeseries(
  File "C:\Users\Stijn.Overmeen\AppData\Roaming\3Di\QGIS3\profiles\testing/python/plugins\threedi_results_analysis\utils\threedi_result_aggregation\base.py", line 164, in prepare_timeseries
    ts_start_time, ts_end_time, tintervals = time_intervals(
  File "C:\Users\Stijn.Overmeen\AppData\Roaming\3Di\QGIS3\profiles\testing/python/plugins\threedi_results_analysis\utils\threedi_result_aggregation\base.py", line 57, in time_intervals
    last_timestamp = threedigrid_object.timestamps[-1]
AttributeError: 'NoneType' object has no attribute 'timestamps'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Stijn.Overmeen\AppData\Roaming\3Di\QGIS3\profiles\testing/python/plugins\threedi_results_analysis\tool_statistics\statistics.py", line 169, in finished
    raise self.exception
  File "C:\Users\Stijn.Overmeen\AppData\Roaming\3Di\QGIS3\profiles\testing/python/plugins\threedi_results_analysis\tool_statistics\statistics.py", line 110, in run
    self.ogr_ds, self.mem_rasts = aggregate_threedi_results(
  File "C:\Users\Stijn.Overmeen\AppData\Roaming\3Di\QGIS3\profiles\testing/python/plugins\threedi_results_analysis\utils\threedi_result_aggregation\base.py", line 1228, in aggregate_threedi_results
    len(node_results["id"]),
KeyError: 'id'

**Traceback 2:**
  File "C:\Users\Stijn.Overmeen\AppData\Roaming\3Di\QGIS3\profiles\testing/python/plugins\threedi_results_analysis\tool_statistics\statistics.py", line 169, in finished
    raise self.exception
  File "C:\Users\Stijn.Overmeen\AppData\Roaming\3Di\QGIS3\profiles\testing/python/plugins\threedi_results_analysis\tool_statistics\statistics.py", line 110, in run
    self.ogr_ds, self.mem_rasts = aggregate_threedi_results(
  File "C:\Users\Stijn.Overmeen\AppData\Roaming\3Di\QGIS3\profiles\testing/python/plugins\threedi_results_analysis\utils\threedi_result_aggregation\base.py", line 1371, in aggregate_threedi_results
    threedigrid_to_ogr(
  File "C:\Users\Stijn.Overmeen\AppData\Roaming\3Di\QGIS3\profiles\testing/python/plugins\threedi_results_analysis\utils\threedi_result_aggregation\threedigrid_ogr.py", line 50, in threedigrid_to_ogr
    layer = tgt_ds.CopyLayer(src_layer, layer_name)
  File "C:\PROGRA~1\3DIMOD~1.28\apps\Python39\lib\site-packages\osgeo\ogr.py", line 827, in CopyLayer
    return _ogr.DataSource_CopyLayer(self, *args, **kwargs)
RuntimeError: failed to prepare SQL: SELECT m."fid", m."geom", m."id", m."display_name", m."calculation_node_id_start", m."calculation_node_id_end", m."source_table_id", m."type", m."bottom_level", m."start_level", m."lower_stop_level", m."capacity" FROM "pump" m WHERE id in (1,)
