### ISSUE TITLE
Statistics: error when selecting ANY variable (e.g. "Node: Lateral discharche")

### ISSUE THREAD

**Issue by benvanbasten-ns** [nens/threedi-results-analysis#876]
1. Select a result in Inputs tab
2. Go to Aggregations tab
3. Select any Variable

Broken since WaterOnStreets merge

Traceback (most recent call last):
  File "C:\Users\ben.vanbasten\AppData\Roaming\3Di\QGIS3\profiles\default/python/plugins\threedi_results_analysis\tool_statistics\threedi_custom_stats_dialog.py", line 280, in method_combobox_text_changed
    self.set_threshold_widget(row=row, method=method)
  File "C:\Users\ben.vanbasten\AppData\Roaming\3Di\QGIS3\profiles\default/python/plugins\threedi_results_analysis\tool_statistics\threedi_custom_stats_dialog.py", line 342, in set_threshold_widget
    if method.threshold_sources:
AttributeError: 'NoneType' object has no attribute 'threshold_sources'

**Comment by benvanbasten-ns** [comment]
Broken since merging of WaterOnStreets

**Comment by arjanverkerk** [comment]
Also, python errors todo with styling when toggling to the last 2 presets.

**Comment by leendertvanwolfswinkel** [comment]
Issue still exists for "Bed level gradient"
