### ISSUE TITLE
Watershed:  adding catchment result when animation styling is selected results in error

### ISSUE THREAD

**Issue by benvanbasten-ns** [nens/threedi-results-analysis#883]
Traceback (most recent call last):
  File "C:\Users\ben.vanbasten\AppData\Roaming\3Di\QGIS3\profiles\default/python/plugins\threedi_results_analysis\tool_watershed\watershed_analysis_dockwidget.py", line 865, in canvasReleaseEvent
    self.gq.upstream_downstream_analysis(
  File "C:\Users\ben.vanbasten\AppData\Roaming\3Di\QGIS3\profiles\default/python/plugins\threedi_results_analysis\tool_watershed\watershed_analysis_dockwidget.py", line 749, in upstream_downstream_analysis
    self.update_analyzed_target_cells(target_node_ids, result_set)
  File "C:\Users\ben.vanbasten\AppData\Roaming\3Di\QGIS3\profiles\default/python/plugins\threedi_results_analysis\tool_watershed\watershed_analysis_dockwidget.py", line 375, in update_analyzed_target_cells
    self.update_layer_filters()
  File "C:\Users\ben.vanbasten\AppData\Roaming\3Di\QGIS3\profiles\default/python/plugins\threedi_results_analysis\tool_watershed\watershed_analysis_dockwidget.py", line 229, in update_layer_filters
    self.target_node_layer.renderer().rootRule().children()[0].setFilterExpression(
AttributeError: 'QgsCategorizedSymbolRenderer' object has no attribute 'rootRule'

**Comment by benvanbasten-ns** [comment]
style is now restored when node is selected
