### ISSUE TITLE
Water balance tool: also allow multi-polygon input

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#885]
When using the map tool to choose a polygon, **Multi**Polygon layers are not shown. 

Please check if the algorithm would work correctly with MultiPolygons. If so, add that geometry type to the filter. If not, we need to make clear to users that they need to convert their data to singlepart

**Comment by leendertvanwolfswinkel** [comment]
@arjanverkerk If my project includes raster layers, I now get this error:

```
An error has occurred while executing Python code: 

AttributeError: 'QgsRasterLayer' object has no attribute 'wkbType' 
Traceback (most recent call last):
  File "C:\Users\leendert.vanwolfswin\AppData\Roaming\3Di\QGIS3\profiles\3Di Results Analysis/python/plugins\threedi_results_analysis\tool_water_balance\views\widgets.py", line 1200, in canvasReleaseEvent
    layer_list = [
  File "C:\Users\leendert.vanwolfswin\AppData\Roaming\3Di\QGIS3\profiles\3Di Results Analysis/python/plugins\threedi_results_analysis\tool_water_balance\views\widgets.py", line 1202, in 
    if layer.wkbType() in POLYGON_TYPES
AttributeError: 'QgsRasterLayer' object has no attribute 'wkbType'
```

**Comment by leendertvanwolfswinkel** [comment]
@arjanverkerk I did some more testing and I realize that what I found is a new bug, unrelated to this fix. I will create a new ticket for that and close this one
