### ISSUE TITLE
Result aggregation: Python error when meta properties are missing

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#889]
In older gridadmin files, meta properties like `has_interflow` may be missing. Please assume that the model contains the hydrological process if the property is missing, i.e., assume `has_interflow=True` if the property `has_interflow` is missing.

Test data here: https://we.tl/t-XHNdlrF5Fv

Error:

```
An error has occurred while executing Python code: 


AttributeError: 'GridH5ResultAdmin' object has no attribute 'has_interflow'
Traceback (most recent call last):
  File "C:\Users\wessel.copier\AppData\Roaming\3Di\QGIS3\profiles\default/python/plugins\threedi_results_analysis\tool_statistics\threedi_custom_stats_dialog.py", line 908, in validate
    containing_information = self._retrieve_model_info()
  File "C:\Users\wessel.copier\AppData\Roaming\3Di\QGIS3\profiles\default/python/plugins\threedi_results_analysis\tool_statistics\threedi_custom_stats_dialog.py", line 794, in _retrieve_model_info
    if self.gr.has_interflow:
AttributeError: 'GridH5ResultAdmin' object has no attribute 'has_interflow'
```

**Comment by arjanverkerk** [comment]
Solved it for the test data supplied for the sake of time, but I would like to note that threedigrids GridResultAdmin could have done a better job by always defining the `has_interflow` attribute.
