### ISSUE TITLE
`TypeError` when switching visualisation on for result with incomplete aggregation netcdf

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#903]
```
TypeError: setCurrentIndex(self, int): argument 1 has unexpected type 'NoneType' 
Traceback (most recent call last):
  File "C:\Users\leendert.vanwolfswin\AppData\Roaming\3Di\QGIS3\profiles\3Di Results Analysis/python/plugins\threedi_results_analysis\tool_animation\map_animator.py", line 168, in results_changed
    self._update_parameter_combo_boxes()
  File "C:\Users\leendert.vanwolfswin\AppData\Roaming\3Di\QGIS3\profiles\3Di Results Analysis/python/plugins\threedi_results_analysis\tool_animation\map_animator.py", line 359, in _update_parameter_combo_boxes
    combo_box.setCurrentIndex(active_idx)
TypeError: setCurrentIndex(self, int): argument 1 has unexpected type 'NoneType'
```

**Comment by arjanverkerk** [comment]
I don't have testdata at hand, but I rewrote the logic so that the apparently intended behaviour actually works. That means that the currently selected parameter stays selected when switching results, if possible.
