### ISSUE TITLE
Processing algorithm "Maximum water depth/level" fails when writing to a temporary result

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#945]

**Comment by leendertvanwolfswinkel** [comment]
```
QGIS version: 3.28.5-Firenze
QGIS code revision: 50adba36f2
Qt version: 5.15.3
Python version: 3.9.5
GDAL version: 3.6.3
GEOS version: 3.11.2-CAPI-1.17.2
PROJ version: Rel. 9.2.0, March 1st, 2023
PDAL version: 2.5.2 (git-version: 57c4e7)
Algorithm started at: 2023-10-25T17:27:19
Algorithm 'Maximum water depth/level raster' starting…
Input parameters:
{ 'DEM_INPUT' : 'C:/Users/leendert.vanwolfswin/Documents/3Di Demo Schematisations/Demo model Langaa/revision 21/schematisation/rasters/Elevation_model_Langaa.tif', 'GRIDADMIN_INPUT' : 'C:\\Users\\leendert.vanwolfswin\\Documents\\3Di Demo Schematisations\\Demo model Langaa\\revision 21\\results\\sim_155509_Demo_Langaa_40_mm_constant_rainfall_in_1_hour\\gridadmin.h5', 'MODE_INPUT' : 0, 'OUTPUT_FILENAME' : 'TEMPORARY_OUTPUT', 'RESULTS_3DI_INPUT' : 'C:\\Users\\leendert.vanwolfswin\\Documents\\3Di Demo Schematisations\\Demo model Langaa\\revision 21\\results\\sim_155509_Demo_Langaa_40_mm_constant_rainfall_in_1_hour\\results_3di.nc' }

Traceback (most recent call last):
File "C:\Users\leendert.vanwolfswin\AppData\Roaming\3Di\QGIS3\profiles\default/python/plugins\threedi_results_analysis\processing\threedidepth_algorithms.py", line 466, in processAlgorithm
calculate_waterdepth(
File "C:\Users\leendert.vanwolfswin\AppData\Roaming\3Di\QGIS3\profiles\default\python\plugins\threedi_results_analysis\deps\threedidepth\calculate.py", line 747, in calculate_waterdepth
with converter_class(**converter_kwargs) as converter:
File "C:\Users\leendert.vanwolfswin\AppData\Roaming\3Di\QGIS3\profiles\default\python\plugins\threedi_results_analysis\deps\threedidepth\calculate.py", line 360, in __enter__
self.target = gdal.GetDriverByName("gtiff").Create(
File "C:\PROGRA~1\3DIMOD~1.28\apps\Python39\lib\site-packages\osgeo\gdal.py", line 2273, in Create
return _gdal.Driver_Create(self, *args, **kwargs)
RuntimeError: Attempt to create new tiff file `TEMPORARY_OUTPUT' failed: Permission denied

Execution failed after 0.95 seconds

Loading resulting layers
Algorithm 'Maximum water depth/level raster' finished
```
