### ISSUE TITLE
Time series plotter: allow users to choose substance concentrations as variable

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#975]
In the nodes/cells plot, users should be able to select the substances that are included in the simulation from the drop-down menu.

See https://threedigrid.readthedocs.io/en/latest/water_quality_results.html for how to use threedigrid on water quality results

- [x] Display the name of the substance in the dropdown menu
- [x] Display the name of the substance as the y axis label

Test data:

https://nelenschuurmans-my.sharepoint.com/:u:/g/personal/leendert_vanwolfswinkel_nelen-schuurmans_nl/EYknplN8Da9Omhl6gWMSX8QBs8Dm0U--ryDKnqdsZhBLVQ?e=ZSplVE

Mock-up:

<img width="1509" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHEzQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8d51e136497779b258ea12c7e61551236ea20929/image.png" alt="image.png" />

**Comment by hoanphungt** [comment]
@leendertvanwolfswinkel I can't open the `water_quality_results_3di.nc` file in the result analysis tool. Do you know why?

**Comment by hoanphungt** [comment]
@leendertvanwolfswinkel 
Can you make a test data with 2 or more substances in the simulation water quality result?

**Comment by leendertvanwolfswinkel** [comment]
Yes, test dataset here: 
[sim_31899_Demo_Dijkring_87-1_Meerssen_#1_-_Contaminated_wastewater_spill.zip](https://github.com/nens/ThreeDiToolbox/files/15486232/sim_31899_Demo_Dijkring_87-1_Meerssen_.1_-_Contaminated_wastewater_spill.zip)


I get the following error with this test dataset:

```
IndexError: Ambiguous result. Field name concentration yields 3 model(s) 
Traceback (most recent call last):
  File "C:\Users\leendert.vanwolfswin\AppData\Roaming\3Di\QGIS3\profiles\3Di Staging/python/plugins\threedi_results_analysis\tool_graph\graph.py", line 81, in run
    new_widget = GraphDockWidget(
  File "C:\Users\leendert.vanwolfswin\AppData\Roaming\3Di\QGIS3\profiles\3Di Staging/python/plugins\threedi_results_analysis\tool_graph\graph_view.py", line 769, in __init__
    parameter_config = self._get_active_parameter_config()
  File "C:\Users\leendert.vanwolfswin\AppData\Roaming\3Di\QGIS3\profiles\3Di Staging/python/plugins\threedi_results_analysis\tool_graph\graph_view.py", line 845, in _get_active_parameter_config
    available_wq_vars = threedi_result.available_water_quality_vars[:]  # a copy
  File "C:\PROGRA~1\3DIMOD~1.34\apps\Python39\lib\functools.py", line 993, in __get__
    val = self.func(instance)
  File "C:\Users\leendert.vanwolfswin\AppData\Roaming\3Di\QGIS3\profiles\3Di Staging/python/plugins\threedi_results_analysis\datasource\threedi_results.py", line 106, in available_water_quality_vars
    model_instance = ga.get_model_instance_by_field_name(concentration_parameter)
  File "C:\Users\leendert.vanwolfswin\AppData\Roaming\3Di\QGIS3\profiles\3Di Staging\python\plugins\threedi_results_analysis\deps\threedigrid\admin\gridadmin.py", line 231, in get_model_instance_by_field_name
    raise IndexError(
IndexError: Ambiguous result. Field name concentration yields 3 model(s)
```

**Comment by leendertvanwolfswinkel** [comment]
@hoanphungt tested again, works great now
You can merge the `water_quality` branch into `refactor` as we are about to do a production release for WQ
