### ISSUE TITLE
(Max) water depth/level processing algorithm: python error when DEM does not have a nodatavalue

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#982]
If the DEM raster does not have a nodatavalue, you will get the Python error shown below. Instead, please:
- Log a warning "The DEM does not have a NODATA value. This may lead to unexpected results."
- Allow the tool to run even if the DEM does not have a nodatavalue

This may need to be fixed in `threedidepth`, not sure. Perhaps passing something like `np.nan` as nodatavalue to threedidepth could be sufficient.

2024-02-28T09:51:01     CRITICAL    Traceback (most recent call last):
              File "C:\Users\leendert.vanwolfswin\AppData\Roaming\3Di\QGIS3\profiles\default/python/plugins\threedi_results_analysis\processing\threedidepth_algorithms.py", line 342, in processAlgorithm
              calculate_waterdepth(
              File "C:\Users\leendert.vanwolfswin\AppData\Roaming\3Di\QGIS3\profiles\default\python\plugins\threedi_results_analysis\deps\threedidepth\calculate.py", line 747, in calculate_waterdepth
              with converter_class(**converter_kwargs) as converter:
              File "C:\Users\leendert.vanwolfswin\AppData\Roaming\3Di\QGIS3\profiles\default\python\plugins\threedi_results_analysis\deps\threedidepth\calculate.py", line 370, in __enter__
              self.target.GetRasterBand(1).SetNoDataValue(self.no_data_value)
              File "C:\PROGRA~1\3DIMOD~1.28\apps\Python39\lib\site-packages\osgeo\gdal.py", line 5005, in SetNoDataValue
              return _gdal.Band_SetNoDataValue(self, value)
             TypeError: in method 'Band_SetNoDataValue', argument 2 of type 'double'

**Comment by hoanphungt** [comment]
@leendertvanwolfswinkel 
Would it be a possible solution to check for the dem_file first in the ThreediToolBox before calling the `calculate_waterdepth` function in the `threedidepth` repo? So that it can check if the DEM has a nodatavalue and if no, assign a value to it (using `np.nan` as you suggested). Or is it better to fix it in the `calculate_waterdepth` function in `threedidepth`?

**Comment by hoanphungt** [comment]
PR to fix the undefined no_data_value issue in the `threedidepth` repo: https://github.com/nens/threedidepth/pull/24

**Comment by hoanphungt** [comment]
Note: check with test data to see why it is still not working

**Comment by hoanphungt** [comment]
It seems that I fixed it in the wrong place in the threedidepth. PR to fix it: https://github.com/nens/threedidepth/pull/26

**Comment by hoanphungt** [comment]
threedidepth is updated to version 0.6.3: https://pypi.org/project/threedidepth/0.6.3/

**Comment by leendertvanwolfswinkel** [comment]
@hoanphungt tested, please merge :)
