### ISSUE TITLE
[Bug]: Certain repositories stop Threedi Result Analysis from launching

### ISSUE THREAD

**Issue by PySjon** [nens/threedi-results-analysis#998]
### Contact Details

sjon.vandijk@nelen-schuurmans.nl

### Complexity

easy

### Priority

low prio

### What happened?

I wanted to launch the threedi-result-analys plugin (v3.6 in QGIS 3.34), but it crashed with the following warnings: 
`2024-04-04T13:49:34     WARNING    Traceback (most recent call last):
              File "C:\Users\Sjon.vanDijk\AppData\Roaming\3Di\QGIS3\profiles\default/python/plugins\threedi_results_analysis\gui\threedi_plugin_dockwidget.py", line 94, in _add_clicked
              self.dialog.refresh()
              File "C:\Users\Sjon.vanDijk\AppData\Roaming\3Di\QGIS3\profiles\default/python/plugins\threedi_results_analysis\gui\threedi_plugin_grid_result_dialog.py", line 222, in refresh
              if num_of_results == 0 and os.path.exists(os.path.join(local_revision.grid_dir, "gridadmin.h5")):
              File "C:\PROGRA~1\3DIMOD~1.34\apps\Python39\lib\ntpath.py", line 78, in join
              path = os.fspath(path)
             TypeError: expected str, bytes or os.PathLike object, not NoneType`

### How to Reproduce?

Add the attached repository (unzip) to the 3Di working directory as defined in your 3Di Models & Simulations plugin. And try to install or open the threedi-result-analysis plugin. If the plugin is already opened, press the green block with white plus button (add result). 

[reest_en_wieden_v2 - v2_boezem_hoogwater_2D_5m (1).zip](https://github.com/nens/ThreeDiToolbox/files/14865913/reest_en_wieden_v2.-.v2_boezem_hoogwater_2D_5m.1.zip)

### What did you expect and what was the actual result?

I expected to start, but it crashes. 

### Add screenshots, video's etc

The maximum size for files is 25MB and the maximum size for images is 10MB.

### Relevant log output

```shell
C:\Users\Sjon.vanDijk\AppData\Roaming\3Di\QGIS3\profiles\default/python/plugins\threedi_results_analysis\gui\threedi_plugin_dockwidget.py", line 94, in _add_clicked
              self.dialog.refresh()
              File "C:\Users\Sjon.vanDijk\AppData\Roaming\3Di\QGIS3\profiles\default/python/plugins\threedi_results_analysis\gui\threedi_plugin_grid_result_dialog.py", line 222, in refresh
              if num_of_results == 0 and os.path.exists(os.path.join(local_revision.grid_dir, "gridadmin.h5")):
              File "C:\PROGRA~1\3DIMOD~1.34\apps\Python39\lib\ntpath.py", line 78, in join
              path = os.fspath(path)
             TypeError: expected str, bytes or os.PathLike object, not NoneType
```

### Additional info

Anything else you would like to share?

**Comment by PySjon** [comment]
[#213](https://github.com/nens/threedi-schematisation-editor/issues/213)

**Comment by PySjon** [comment]
@leendertvanwolfswinkel
